[project]
name = "yt-dlp-web"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.1",
    "yt-dlp>=2025.5.22",
]
