[project]
name = "yt-dlp-web"
version = "0.1.0"
description = "Web GUI for yt-dlp"
readme = "README.md"
requires-python = ">=3.13.3"
dependencies = [
    "flask>=3.1.1",
    "yt-dlp>=2025.5.22",
    "gunicorn>=23.0.0",
]
